name: Feature Engineering

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  feature-engineering:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install hopsworks pandas scikit-learn lightgbm mlflow

    - name: Run Feature Engineering Script
      run: |
        python feature_engineering.py  # Assuming you have a script for feature engineering

    - name: Commit and Push Processed Data (Optional)
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your.email@example.com"
        git add processed_data.csv
        git commit -m "Add processed data for feature engineering"
        git push
