name: Inference

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  inference:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install hopsworks pandas scikit-learn lightgbm mlflow

    - name: Run Inference Script
      run: |
        python inference.py  # Assuming you have a script for inference

    - name: Commit and Push Inference Results (Optional)
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your.email@example.com"
        git add inference_results.csv
        git commit -m "Add inference results"
        git push
